// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmdnaaclpkgxxportnuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZG5hYWNscGtneHhwb3J0bnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzQyNzcsImV4cCI6MjA2OTM1MDI3N30.hFh9dR4oo-ZG_LKaLMYyBK-qQKreEBTJqFBxFLqKRig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});